/pcloud_to_map:
  ros__parameters:
    cloud_max_x: 10.0
    cloud_max_z: 16.0
    cloud_min_x: -10.0
    cloud_min_z: -5.0
    free_thresh: 0.55
    occupied_thresh: 0.5
    resize_factor: 5.0
    scale_factor: 10.0
    thresh_diff: 0.01
    use_sim_time: false
    visit_thresh: 0.0
    qos_overrides:
      /parameter_events:
        publisher:
          depth: 1000
          durability: volatile
          history: keep_last
          reliability: reliable