/**/pcloud_to_map:
  ros__parameters:
    scale_factor: 1.0
    resize_factor: 1.0
    cloud_max_x: 10.0
    cloud_min_x: -10.0
    cloud_max_z: 16.0
    cloud_min_z: -5.0
    free_thresh: 0.55
    occupied_thresh: 0.5
    thresh_diff: 0.01
    use_local_counters: 1
    visit_thresh: 5.0
    use_gaussian_counters: 1
    use_boundary_detection: true
    use_height_thresholding: true
    qos_overrides:
      /parameter_events:
        publisher:
          depth: 1000
          durability: volatile
          history: keep_last
          reliability: reliable